### PR TITLE
Make date formats more flexible

### PR DESCRIPTION
**Pull request by paciorek**
This sets the default date format to ISO 8601  `yyyy-MM-dd` but allows users to set `date-format` in `config.yml` to other formats handled by https://deno.land/std/datetime/mod.ts.

Also updates README to show examples using ISO 8601. I think there is a good argument to use this, in part because US 'MM/dd/YY' is ambiguous.

### CODE REVIEW

**Comment by paciorek** [comment]
Fixes #5

**Comment by andrewpbray** [comment]
@paciorek Could you merge main into this branch so get the commits from the logging PR that was approved? Doesn't look like I'm able to resolve the conflict on your branch.

**Comment by paciorek** [comment]
@andrewpbray done.

**Comment by andrewpbray** [comment]
thanks!

**Pull request merged**
